language: php

notifications:
    email:
        on_success: never

php:
    - 7.3
    - 7.4

matrix:
    fast_finish: true
    include:
        -   php: 7.3
            env: dependencies=lowest

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install -n
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
    - composer test-coverage
    - vendor/bin/phpunit

after_script:
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master
